# Generated by Django 4.2.7 on 2023-11-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_alter_cropdata_harvest_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropdata',
            name='planting_date',
            field=models.DateField(null=True),
        ),
    ]
