# Generated by Django 4.2.7 on 2023-11-23 11:05

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_cropdata_date_created_cropdata_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmdata',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='farmdata',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cropdata',
            name='harvest_date',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='cropdata',
            name='planting_date',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='farmdata',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
